<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="TestVagrants-MacBook-Pro-2.local" ignored="0" name="Gradle test" tests="3" failures="1" timestamp="09 Jun 2020 12:37:14 GMT" time="15.356" errors="0">
  <testcase name="validateGetEmployeesApi" time="12.621" classname="EmployeesApiTests.DummyRestEmployeesApiTest"/>
  <testcase name="validatePostEmployeeApi" time="1.6" classname="EmployeesApiTests.DummyRestEmployeesApiTest"/>
  <testcase name="validateUpdateEmployeeApi" time="0.963" classname="EmployeesApiTests.DummyRestEmployeesApiTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at EmployeesApiTests.DummyRestEmployeesApiTest.validateUpdateEmployeeApi(DummyRestEmployeesApiTest.java:54)
at com.sun.proxy.$Proxy2.stop(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 46 stack frames]]>
    </failure>
  </testcase> <!-- validateUpdateEmployeeApi -->
</testsuite> <!-- Gradle test -->
